name: Dispatch workflow

on:
  issues:
    types:
      - reopened
      - closed
  pull_request_target:
    types:
      - reopened
      - closed
      # Makes sure we always add status check for PRs. Useful only if
      # this action is required to pass before merging. Can be removed
      # otherwise.
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/dispatches
          owner: luwol03
          repo: main-project
          event_type: synchronize-remote
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
