name: Dispatch workflow

on:
  issues:
    types:
      - opened
      - edited
      - reopened
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      # Makes sure we always add status check for PRs. Useful only if
      # this action is required to pass before merging. Can be removed
      # otherwise.
      - synchronize

  # Schedule a daily check. Useful if you reference cross-repository
  # issues or pull requests. Can be removed otherwise.
  schedule:
    - cron: '0 0 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/dispatches
          owner: luwol03
          repo: main-project
          event_type: synchronize-remote
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
